#!/bin/bash

archive="ic-$(date +%s).epub"
date=$(date +"%Y-%m-%dT%TZ")

# update modifed date
sed -r -i "s/[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:]*Z/$date/" OEBPS/content.opf

mkdir /tmp/epub
cp -r ./* /tmp/epub

dir=$(pwd)
cd /tmp/epub

# compact files
find -name '*.xhtml' -exec htmlcompressor '{}' -o '{}' \;
find -name '*.css' -exec htmlcompressor '{}' -o '{}' \;
find -name '*.opf' -exec htmlcompressor '{}' -o '{}' \;
find -name '*.ncx' -exec htmlcompressor '{}' -o '{}' \;

zip -0 -X ../$archive mimetype
zip -r ../$archive META-INF OEBPS

cd "$dir"
mv /tmp/$archive ../

epubcheck ../$archive &> ../log

rm -rf /tmp/epub
