#!/bin/bash

archive="../ic-$(date +%s).epub"
date=$(date +"%Y-%m-%dT%TZ")

# update modifed date
sed -r -i "s/[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:]*Z/$date/" OEBPS/content.opf

zip -0 -X $archive mimetype
zip -r $archive META-INF OEBPS

epubcheck $archive &> ../log
