#!/bin/sh
# $Id$
# $Date: Mon 29 Apr 2013 08:50:28 AM UTC $
# Jeremiah Dow <jeremdow@gmail.com>
#
# Prints the average transfer rates since last run to stdout.
# If used with tmux, dwm, etc, it can be run over any interval.
#
# Usage: netawk [interface] [cache]

iface=${1-eth0}
cache=${2-/tmp/netawk}

if [ ! -f $cache ]
then
	echo $(grep $iface /proc/net/dev | \
		awk '{ print $2, $10 }') > $cache
fi

lastcheck=$(stat -c %Z $cache)
(( interval=$(date +%s)-$lastcheck ))

echo $(grep $iface /proc/net/dev | \
	awk '{ print $2, $10 }') >> $cache

awk ' {
	rxa[NR]=$1;
	txa[NR]=$2;
}

END {
	if ('$interval') {
		rx=(rxa[2]-rxa[1])/1024/'$interval';
		tx=(txa[2]-txa[1])/1024'$interval';
	}

	if (rx > 1024) {
		rx=sprintf("%.2fMB/s", rx/1024);
	}
	else {
		rx=sprintf("%.0fKb/s", rx)
	}

	if (tx > 1024) {
		tx=sprintf("%.2fMB/s", tx/1024);
	}
	else {
		tx=sprintf("%.0fKb/s", tx)
	}

	printf("↓%s ↑%s\n", rx, tx);
}
' $cache

echo $(grep $iface /proc/net/dev | \
	awk '{ print $2, $10 }') > $cache
