#!/bin/sh
# $Id$
# $Date: Mon 29 Apr 2013 01:15:22 PM UTC $

echo $(uptime | tac -s : | head -1 | sed -r 's/,//g') \
	$(netawk) \
	$(free -m | grep + | awk '{ print $3 }')MB \
	/:$(df -h | grep /dev/xvda | awk '{ print $5 }')
