#!/bin/sh
# $Id$
# $Date: Sat 06 Sep 2014 04:25:52 AM UTC $
# Jeremiah Dow <jeremdow@gmail.com>
#
# current conditions from Google in degrees fahrenheit
#
# Usage: weather [city]

# set your browser (links or similar text browser)
browser='links'
# set your default city
city='boston'

$browser -dump "http://www.google.com/search?hl=en&q=weather+$(echo ${@:-$city} | tr ' ' '+')" |
grep -m1 -o '[0-9]*DEGF'
